TOP=../../../..
DIRNAME=src/modules/OGIModules/OGIinsert

H =

SRCS = insert.cc 

OBJS = $(SRCS:.cc=.o)
 
FILES = Makefile $(SRCS) $(H)
 
LOCAL_INCLUDES = -I../OGIcommon -I../../../src/include 

 
INLIB = $(TOP)/src/lib/libFestival.a
 
ALL = .buildlib
 
include $(TOP)/config/common_make_rules
